version: '3.4'
services:
  db:
    image: linuxserver/mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234

  back:
    image: wartski/back_nestjs:v1.1.0
    ports:
      - 3000:3000
    environment:
      PORT: 3306
      HOST: db
      DATABASE: database
      USER: root
      PASS: 1234
    depends_on:
      - db

  front:
    image: wartski/front_angularjs:v1.1.0
    ports:
      - 4000:4000
    environment:
      API: http://localhost:3000/api
