apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  capacity:
    storage: 100M
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: disco-pedro
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  labels:
    type: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  volumeName: mysql