apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-angularjs
  labels:
    app: front-angularjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-angularjs
  template:
    metadata:
      labels:
        app: front-angularjs
    spec:
      containers:
      - name: front-angularjs
        image: wartski/front_angularjs:v2.0.0
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: front-configs
              key: PORT
        - name: API
          valueFrom:
            configMapKeyRef:
              name: front-configs
              key: API