apiVersion: v1
kind: Service
metadata:
  name: front-angularjs
  labels:
    app: front-angularjs
spec:
  type: NodePort
  selector:
    app: front-angularjs
  ports:
    - protocol: TCP
      nodePort: 30100
      port: 4000